### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ghost** [MrPowerGamerBR/AminoREAPI#13]
Hey so, somewhat unrelated to the project, but basically I've been trying to get Amino running on Android x86.
Android x86 seems to be blocked from generating valid device id's though, which set me on a journey to get everything back running by constantly playing pong with packages, but either way, the webapp of Amino doesn't record a device_id anymore, at least from my testin. Only "session" and "sid", both completely missing the mark.
Most issues in here are unanswered and most activity seems to have stopped here, the forks also show nothing interesting, is this dead?

**Comment by beryll1um** [comment]
Yes. This project has long been abandoned. I recently started developing my solution on typescript. A lot of things are ready, but a lot of things can be done, to fix. If you're interested, see my account.

**Comment by ghost** [comment]
Alright, thanks for your support.
I'll close the issue now.
