### ISSUE TITLE
Is this API still updated?

### ISSUE THREAD

**Issue by SrZorro** [MrPowerGamerBR/AminoREAPI#5]
Looks like Amino now uses https, so i can't find a way to intercept my deviceID, also all my tests using the API here return a 400 error. Its still working for anyone or its broken?

**Comment by coffeeboo** [comment]
400 would mean, of course, you are not authenticated. 
[Try this,](https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=en_US) which uses man-in-the-middle techniques to intercept HTTPS anyway.

**Comment by coffeeboo** [comment]
Also, as the Device ID isn't anything special or secure, this API should have a default one.
@MrPowerGamerBR

**Comment by MrPowerGamerBR** [comment]
It may be something special, we never know, maybe they can Device ID ban,
they already denies registering of multiple accounts in the same device ID.

Em qua, 6 de jun de 2018 12:31, Jason Idris <notifications@github.com>
escreveu:

**Comment by SrZorro** [comment]
Thanks @coffeeboo for that link.

Closed as [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK) error.
